### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by chillingstar** [yasserprogamer/Carbon23#1]
Hey brother, did you seriously leave Discord? :(

**Comment by chillingstar** [comment]
![image](https://user-images.githubusercontent.com/72331969/210365290-31591a81-ff10-4dc9-ba87-8c2fc46dcc45.png)
btw Sava became a terrorist

**Comment by yasserprogamer** [comment]
Well yeah, I left Discord seriously. Sorry!

**Comment by yasserprogamer** [comment]
I do not think I'll be back to Discord unless I change my mind.
